/******************************************************************************
 Group: CMCU LPRF
 $Target Device: DEVICES $

 ******************************************************************************
 $License: BSD3 2024 $
 ******************************************************************************
 $Release Name: PACKAGE NAME $
 $Release Date: PACKAGE RELEASE DATE $
 *****************************************************************************/

/*
 *  ======== ti_zigbee_config.h.xdt ========
 */
/*
 *                           ti_zigbee_config.h
 *
 *  DO NOT EDIT - This file was generated by the SysConfig tool.
 *
 *  Macros used to define a TI Z-Stack ZigBee device.
 *
 */

#ifndef TI_ZIGBEE_CONFIG_H
#define TI_ZIGBEE_CONFIG_H

#ifdef __cplusplus
extern "C"
{
#endif


/******************************************************************************
 * INCLUDES
 */
/******************************************************************************
 * CONSTANTS
 */

/******************************************************************************
 * CONFIGURATION
 */

#ifndef CHANNEL_LIST
#define CHANNEL_LIST            {11,17,26}
#endif



#ifndef GPD_APP_ID_TYPE
#define GPD_APP_ID_TYPE         0
#endif

#ifndef GPD_SRC_ID
#define GPD_SRC_ID              0xabacadac
#endif

#ifndef SECURITY_LEVEL
#define SECURITY_LEVEL          3
#endif

#ifndef SECURITY_KEY_TYPE
#define SECURITY_KEY_TYPE       4
#endif

#ifndef SECURITY_KEY
#define SECURITY_KEY            {0xCF,0xCE,0xCD,0xCC,0xCB,0xCA,0xC9,0xC8,0xC7,0xC6,0xC5,0xC4,0xC3,0xC2,0xC1,0xC0}
#endif

#ifndef GPDF_REPETITIONS
#define GPDF_REPETITIONS        3
#endif

#ifndef UNIDIR_DEVICE
#define UNIDIR_DEVICE           ZB_FALSE
#endif

#ifndef BATTERYLESS_DEVICE
#define BATTERYLESS_DEVICE      ZB_FALSE
#endif

#ifdef __cplusplus
}  /* end of extern "C" */
#endif

#endif /* TI_ZIGBEE_CONFIG_H */